# Generated by Django 3.1.5 on 2021-05-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_movido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='17/05/2021', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_movimiento',
            field=models.CharField(blank=True, default='17/05/2021', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='17/05/2021 23:51:44 hs', editable=False, max_length=200),
        ),
    ]
