# Generated by Django 3.1.5 on 2021-04-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='is_active',
            field=models.CharField(blank=True, default='S', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='07/04/2021 21:30:04 hs', editable=False, max_length=200),
        ),
    ]
