# Generated by Django 3.1.5 on 2021-05-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20210510_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='10/05/2021 20:34:38 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_movimiento',
            field=models.CharField(blank=True, default='10/05/2021 20:34:38 hs', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='10/05/2021 20:34:38 hs', editable=False, max_length=200),
        ),
    ]
