# Generated by Django 3.1.5 on 2021-04-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20210407_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='14/04/2021 19:54:12 hs', editable=False, max_length=200),
        ),
    ]
