# Generated by Django 3.1.5 on 2021-06-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20210615_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021 22:55:22 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021 22:55:22 hs', editable=False, max_length=200),
        ),
    ]
