# Generated by Django 3.1.5 on 2021-05-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20210509_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='09/05/2021 21:23:05 hs', editable=False, max_length=200),
        ),
    ]
