# Generated by Django 3.1.5 on 2021-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20210515_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='15/05/2021 12:23:11 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_movimiento',
            field=models.CharField(blank=True, default='15/05/2021 12:23:11 hs', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='15/05/2021 12:23:11 hs', editable=False, max_length=200),
        ),
    ]
