# Generated by Django 3.1.5 on 2021-05-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20210517_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='is_active',
            field=models.CharField(blank=True, default='S', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='deposito',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productostock',
            name='is_active',
            field=models.CharField(blank=True, default='S', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='productostock',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tipoproducto',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='18/05/2021', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_movimiento',
            field=models.CharField(blank=True, default='18/05/2021', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='18/05/2021 23:15:46 hs', editable=False, max_length=200),
        ),
    ]
