# Generated by Django 3.1.5 on 2021-06-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20210615_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021 23:26:15 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021 23:26:15 hs', editable=False, max_length=200),
        ),
    ]
