# Generated by Django 3.1.5 on 2021-06-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20210609_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_fisico',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='09/06/2021 22:57:02 hs', editable=False, max_length=200),
        ),
    ]
