# Generated by Django 3.1.5 on 2021-03-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20210304_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.PositiveIntegerField(help_text='Ingrese precio de compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.PositiveIntegerField(help_text='Ingrese precio de venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(help_text='Ingrese stock minimo'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='30/03/2021 21:19:31 hs', editable=False, max_length=200),
        ),
    ]
