# Generated by Django 3.1.5 on 2021-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20210515_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='16/05/2021 16:03:56 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_movimiento',
            field=models.CharField(blank=True, default='16/05/2021 16:03:56 hs', max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='16/05/2021 16:03:56 hs', editable=False, max_length=200),
        ),
    ]
