# Generated by Django 3.1.5 on 2021-05-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20210526_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='26/05/2021 23:36:43 hs', editable=False, max_length=200),
        ),
    ]
