# Generated by Django 3.1.5 on 2021-03-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20210330_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='30/03/2021 23:48:29 hs', editable=False, max_length=200),
        ),
    ]
