# Generated by Django 3.1.5 on 2021-06-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20210609_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_vencido',
            field=models.CharField(blank=True, default='S', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='09/06/2021 23:22:02 hs', editable=False, max_length=200),
        ),
    ]
