# Generated by Django 3.1.5 on 2021-06-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210620_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='21/06/2021 22:38:18 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='21/06/2021', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.CharField(blank=True, default='0', help_text='Ingrese precio de compra', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='21/06/2021 22:38:18 hs', editable=False, max_length=200),
        ),
    ]
