# Generated by Django 3.1.5 on 2021-05-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210526_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='28/05/2021', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='28/05/2021 21:07:59 hs', editable=False, max_length=200),
        ),
    ]
