# Generated by Django 3.1.5 on 2021-04-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210330_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='03/04/2021 22:36:09 hs', editable=False, max_length=200),
        ),
    ]
