# Generated by Django 3.1.5 on 2021-05-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20210528_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='29/05/2021', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(help_text='Ingrese precio de compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(help_text='Ingrese precio de venta'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='29/05/2021 15:40:41 hs', editable=False, max_length=200),
        ),
    ]
