# Generated by Django 3.1.5 on 2021-04-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20210403_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='03/04/2021 22:38:31 hs', editable=False, max_length=200),
        ),
    ]
