# Generated by Django 3.1.5 on 2021-06-22 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20210621_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='21/06/2021 23:10:47 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='21/06/2021 23:10:47 hs', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='HistoricoProductoPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.CharField(default='21/06/2021', max_length=500, null=True)),
                ('precio_compra', models.CharField(blank=True, max_length=500, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
