# Generated by Django 3.1.5 on 2021-06-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20210612_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='12/06/2021 20:06:41 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='12/06/2021 20:06:41 hs', editable=False, max_length=200),
        ),
    ]
