# Generated by Django 3.1.5 on 2021-05-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20210529_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.CharField(help_text='Ingrese precio de compra', max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.CharField(help_text='Ingrese precio de venta', max_length=500),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='29/05/2021 15:46:35 hs', editable=False, max_length=200),
        ),
    ]
