# Generated by Django 3.1.5 on 2021-05-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_auto_20210529_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='servicio_o_producto',
            field=models.CharField(blank=True, default='P', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='30/05/2021', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='30/05/2021 17:42:24 hs', editable=False, max_length=200),
        ),
    ]
