# Generated by Django 3.1.5 on 2021-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_auto_20210622_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra_viejo',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='22/06/2021 21:54:51 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='22/06/2021 21:54:51 hs', editable=False, max_length=200),
        ),
    ]
