# Generated by Django 3.1.5 on 2021-05-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_auto_20210530_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_servicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='30/05/2021 18:08:41 hs', editable=False, max_length=200),
        ),
    ]
