# Generated by Django 3.1.5 on 2021-04-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_auto_20210403_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='03/04/2021 22:58:19 hs', editable=False, max_length=200),
        ),
    ]
