# Generated by Django 3.1.5 on 2021-05-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0012_auto_20210530_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_deposito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.deposito'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.tipoproducto'),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='30/05/2021 18:14:38 hs', editable=False, max_length=200),
        ),
    ]
