# Generated by Django 3.1.5 on 2021-07-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_auto_20210707_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='07/07/2021 22:12:14 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='07/07/2021 22:12:14 hs', editable=False, max_length=200),
        ),
    ]
