# Generated by Django 3.1.5 on 2021-06-05 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('producto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCabeceraVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_timbrado', models.CharField(max_length=500, null=True)),
                ('nro_factura', models.CharField(max_length=500, null=True)),
                ('fecha_inicio_timbrado', models.CharField(max_length=500, null=True)),
                ('fecha_fin_timbrado', models.CharField(max_length=500, null=True)),
                ('ruc_empresa', models.CharField(max_length=500, null=True)),
                ('fecha_emision', models.CharField(default='05/06/2021', max_length=500, null=True)),
                ('tipo_factura', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default=('PENDIENTE', 'Pendiente'), max_length=500)),
                ('total_iva', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('factura_cargada', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=2, null=True)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'verbose_name': 'Factura Venta',
                'verbose_name_plural': 'Facturas Ventas',
                'permissions': (('add_facturacabeceraventa', 'Agregar Factura Venta'), ('change_facturacabeceraventa', 'Editar Factura Venta'), ('delete_facturacabeceraventa', 'Anular Factura Venta'), ('view_facturacabeceraventa', 'Listar Facturas Ventas')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Plural',
            },
        ),
        migrations.CreateModel(
            name='ProductoServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.servicio')),
            ],
            options={
                'permissions': (('add_productoservicios', 'Agregar Producto Servicios'), ('change_productoservicios', 'Editar Producto Servicios'), ('delete_productoservicios', 'Eliminar Producto Servicios'), ('view_productoservicios', 'Listar Productos y Servicios')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=800)),
                ('id_factura_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.facturacabeceraventa')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
