# Generated by Django 3.1.5 on 2021-05-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_auto_20210526_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadetalleventa',
            name='id_producto_servicio',
        ),
    ]
