# Generated by Django 3.1.5 on 2021-05-27 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_confiempresa_ruc_empresa'),
        ('producto', '0006_auto_20210526_2329'),
        ('factura', '0003_remove_facturadetalleventa_id_producto_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalleventa',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturadetalleventa',
            name='id_servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configuracion.servicio'),
            preserve_default=False,
        ),
    ]
