# Generated by Django 3.1.5 on 2021-06-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20210616_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacabeceraventa',
            name='total_formateado',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='16/06/2021 21:27:00 hs', max_length=500, null=True),
        ),
    ]
