# Generated by Django 3.1.5 on 2021-05-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210526_2336'),
        ('configuracion', '0005_confiempresa_ruc_empresa'),
        ('factura', '0004_auto_20210526_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalleventa',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='facturadetalleventa',
            name='id_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.servicio'),
        ),
    ]
