# Generated by Django 3.1.5 on 2021-06-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_auto_20210616_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacabeceraventa',
            name='factura_reporte_cantidad_mes',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_alta',
            field=models.CharField(default='19/06/2021', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='19/06/2021 19:12:28 hs', max_length=500, null=True),
        ),
    ]
