# Generated by Django 3.1.5 on 2021-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_auto_20210526_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadetalleventa',
            name='id_servicio',
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='30/05/2021', max_length=500, null=True),
        ),
    ]
