# Generated by Django 3.1.5 on 2021-06-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_auto_20210619_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalleventa',
            name='detalle_cargado_mes',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='19/06/2021 19:41:26 hs', max_length=500, null=True),
        ),
    ]
