# Generated by Django 3.1.5 on 2021-06-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20210530_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='02/06/2021', max_length=500, null=True),
        ),
    ]
