# Generated by Django 3.1.5 on 2021-06-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20210619_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacabeceraventa',
            name='factura_servicio_reporte',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='facturadetalleventa',
            name='detalle_cargado_servicio',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_alta',
            field=models.CharField(default='20/06/2021', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='20/06/2021 12:29:09 hs', max_length=500, null=True),
        ),
    ]
