# Generated by Django 3.1.5 on 2021-06-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_auto_20210620_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalleventa',
            name='subtotal',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_alta',
            field=models.CharField(default='28/06/2021', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='28/06/2021 16:00:56 hs', max_length=500, null=True),
        ),
    ]
