# Generated by Django 3.1.5 on 2021-07-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_auto_20210628_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_alta',
            field=models.CharField(default='07/07/2021', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='07/07/2021 22:07:13 hs', max_length=500, null=True),
        ),
    ]
