# Generated by Django 3.1.5 on 2021-07-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0009_auto_20210707_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='07/07/2021 22:12:14 hs', max_length=500, null=True),
        ),
    ]
