# Generated by Django 2.1 on 2021-02-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(help_text='Ingrese nombre de la mascota', max_length=200)),
                ('tatuaje', models.CharField(blank=True, default='-', help_text='Ingrese el tatuaje', max_length=200, null=True)),
                ('sexo', models.CharField(choices=[('MAC', 'Macho'), ('HEB', 'Hembra')], default='-', help_text='Seleccione el sexo', max_length=15)),
                ('edad', models.IntegerField(blank=True, default=0, help_text='Ingrese la edad', null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Ingrese una foto', null=True, upload_to='mascotas/fotos')),
                ('peso', models.IntegerField(help_text='Ingrese el peso')),
                ('fecha_nacimmiento', models.DateField(blank=True, default='11/11/1111', help_text='Ingrese la fecha de nacimiento', null=True)),
            ],
        ),
    ]
