# Generated by Django 3.1.5 on 2021-06-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20210612_2343'),
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antiparasitario',
            name='id_ficha_medica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.fichamedica'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id_ficha_medica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.fichamedica'),
        ),
        migrations.AlterField(
            model_name='historicofichamedica',
            name='vacuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.tipovacuna'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='id_vacuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.tipovacuna'),
        ),
    ]
