# Generated by Django 3.1.5 on 2021-03-05 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 4, 22, 35, 31, 961098)),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 4, 22, 35, 31, 962096)),
        ),
        migrations.AlterField(
            model_name='raza',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 4, 22, 35, 31, 961098)),
        ),
    ]
