# Generated by Django 3.1.5 on 2021-07-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_historicofichamedica_id_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='masc_reservado',
            field=models.CharField(blank=True, default='S', max_length=200, null=True),
        ),
    ]
