# Generated by Django 3.1.5 on 2021-06-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20210613_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofichamedica',
            name='fecha_alta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
