# Generated by Django 3.1.5 on 2021-07-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_mascota_masc_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicofichamedica',
            name='historico_cargado_reporte',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
    ]
