# Generated by Django 3.1.5 on 2021-06-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_historicofichamedica_fecha_alta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='fecha_proxima_consulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='fecha_ultima_consulta',
        ),
    ]
