# Generated by Django 2.1 on 2021-03-01 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_auto_20210228_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 22, 40, 28, 250747)),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 22, 40, 28, 251744)),
        ),
        migrations.AlterField(
            model_name='raza',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 22, 40, 28, 250747)),
        ),
    ]
