# Generated by Django 2.1 on 2021-03-01 01:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20210228_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 1, 1, 42, 3, 518208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 1, 1, 42, 3, 519184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='raza',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 1, 1, 42, 3, 518208, tzinfo=utc)),
        ),
    ]
