# Generated by Django 3.1.5 on 2021-07-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_historicofichamedica_historico_cargado_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha_reservada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='hora_reserva',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
