# Generated by Django 2.1 on 2021-03-01 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_auto_20210228_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 22, 46, 28, 760359)),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 22, 46, 28, 761356)),
        ),
        migrations.AlterField(
            model_name='raza',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 28, 22, 46, 28, 761356)),
        ),
    ]
