# Generated by Django 3.1.5 on 2021-04-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=200)),
                ('apertura', models.CharField(max_length=200)),
                ('cierre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Configuracion Empresa',
                'verbose_name_plural': 'Configuraciones Empresas',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_serv', models.CharField(max_length=200)),
                ('nombre_servicio', models.CharField(help_text='Ingrese nombre del servicio', max_length=200)),
                ('precio_servicio', models.CharField(help_text='Ingrese el precio del servicio', max_length=200)),
                ('min_sev', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
