# Generated by Django 3.1.5 on 2021-06-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confiempresa',
            name='dias_a_vencer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
