# Generated by Django 3.1.5 on 2021-05-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confiempresa',
            name='apertura',
        ),
        migrations.RemoveField(
            model_name='confiempresa',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='confiempresa',
            name='semana',
        ),
        migrations.AddField(
            model_name='confiempresa',
            name='apertura_caja_inicial',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='confiempresa',
            name='id_confi',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='confiempresa',
            name='ubicacion_deposito_inicial',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
    ]
