# Generated by Django 3.1.5 on 2021-06-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(blank=True, max_length=500, null=True)),
                ('periodo_aplicaion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
