# Generated by Django 3.1.5 on 2021-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_confiempresa_dias_a_vencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confiempresa',
            name='dias_a_vencer',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
