# Generated by Django 3.1.5 on 2021-06-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_tipovacuna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovacuna',
            old_name='periodo_aplicaion',
            new_name='periodo_aplicacion',
        ),
    ]
