# Generated by Django 3.1.5 on 2021-06-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20210612_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipovacuna',
            options={'default_permissions': (), 'permissions': (('add_tipovacuna', 'Agregar Vacuna'), ('change_tipovacuna', 'Editar Vacuna'), ('delete_tipovacuna', 'Eliminar Vacuna'), ('view_tipovacuna', 'Listar Vacunas')), 'verbose_name': 'Vacunas', 'verbose_name_plural': 'Vacunas'},
        ),
    ]
