# Generated by Django 3.1.5 on 2021-06-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20210620_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipovacuna',
            name='multi_aplicaciones',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
    ]
