# Generated by Django 3.1.5 on 2021-05-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20210525_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='confiempresa',
            name='ruc_empresa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
