# Generated by Django 3.1.5 on 2021-07-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_confiempresa_dias_alert_vacunas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='emp_disponible_reserva',
            field=models.CharField(blank=True, default='N', max_length=200, null=True),
        ),
    ]
