# Generated by Django 3.1.5 on 2021-07-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_empleado_emp_disponible_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='emp_disponible_reserva',
            field=models.CharField(blank=True, default='S', max_length=200, null=True),
        ),
    ]
