# Generated by Django 3.1.5 on 2021-06-15 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20210614_2315'),
        ('utiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
