# Generated by Django 3.1.5 on 2021-06-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20210616_2024'),
        ('utiles', '0003_productocomprados'),
    ]

    operations = [
        migrations.CreateModel(
            name='GananciaPorMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mes', models.IntegerField(blank=True, null=True)),
                ('label_mes', models.CharField(blank=True, max_length=500, null=True)),
                ('total_mes', models.CharField(blank=True, max_length=600, null=True)),
                ('id_factura_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.facturacabeceraventa')),
            ],
        ),
    ]
