# Generated by Django 3.1.5 on 2021-06-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utiles', '0004_gananciapormes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gananciapormes',
            name='total_mes_formateado',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='gananciapormes',
            name='total_mes',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
