# Generated by Django 3.1.5 on 2021-06-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20210619_1916'),
        ('utiles', '0005_auto_20210616_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVendidoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mes', models.IntegerField(blank=True, null=True)),
                ('label_mes', models.CharField(blank=True, max_length=500, null=True)),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCompradoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mes', models.IntegerField(blank=True, null=True)),
                ('label_mes', models.CharField(blank=True, max_length=500, null=True)),
                ('cantidad_comprada_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
