# Generated by Django 3.1.5 on 2021-06-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210620_1226'),
        ('utiles', '0006_productocompradomes_productovendidomes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioVendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
