# Generated by Django 3.1.5 on 2021-06-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utiles', '0008_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_ruc', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_alta', models.CharField(blank=True, default='23/06/2021 22:46:25 hs', max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cedula',
            name='fecha_alta',
            field=models.CharField(blank=True, default='23/06/2021 22:46:25 hs', max_length=500, null=True),
        ),
    ]
