# Generated by Django 3.1.5 on 2021-06-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utiles', '0009_auto_20210623_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gananciapormes',
            name='anho',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cedula',
            name='fecha_alta',
            field=models.CharField(blank=True, default='26/06/2021 18:25:31 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ruc',
            name='fecha_alta',
            field=models.CharField(blank=True, default='26/06/2021 18:25:31 hs', max_length=500, null=True),
        ),
    ]
