# Generated by Django 3.1.5 on 2021-06-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='is_active',
            field=models.CharField(blank=True, default='S', max_length=2, null=True),
        ),
    ]
