# Generated by Django 3.1.5 on 2021-05-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturacompra',
            old_name='fecha_vecimiento',
            new_name='fecha_vencimiento',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='16/05/2021 00:08:24 hs', editable=False, max_length=200),
        ),
    ]
