# Generated by Django 3.1.5 on 2021-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='factura_cargada_producto',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='18/05/2021 21:19:53 hs', editable=False, max_length=200),
        ),
    ]
