# Generated by Django 3.1.5 on 2021-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='fecha_emision_factura',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='06/06/2021 15:18:57 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidocabecera',
            name='fecha_alta',
            field=models.CharField(default='06/06/2021', editable=False, max_length=200),
        ),
    ]
