# Generated by Django 3.1.5 on 2021-06-16 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20210615_2255'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='detalle_cargado_reporte',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021 22:55:22 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='pedidocabecera',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='id_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedido'),
        ),
    ]
