# Generated by Django 3.1.5 on 2021-06-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210615_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='pedidod_to_factura',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021 23:13:28 hs', editable=False, max_length=200),
        ),
    ]
