# Generated by Django 3.1.5 on 2021-05-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210518_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido_cargado',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='18/05/2021 21:49:21 hs', editable=False, max_length=200),
        ),
    ]
