# Generated by Django 3.1.5 on 2021-06-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210606_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='fecha_alta',
            field=models.CharField(default='09/06/2021', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='09/06/2021 18:50:44 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidocabecera',
            name='fecha_alta',
            field=models.CharField(default='09/06/2021', editable=False, max_length=200),
        ),
    ]
