# Generated by Django 3.1.5 on 2021-05-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20210518_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='18/05/2021 22:25:49 hs', editable=False, max_length=200),
        ),
    ]
