# Generated by Django 3.1.5 on 2021-06-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20210615_2326'),
        ('compras', '0003_auto_20210615_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='id_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='15/06/2021 23:26:15 hs', editable=False, max_length=200),
        ),
    ]
