# Generated by Django 3.1.5 on 2021-05-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210518_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='18/05/2021 23:15:34 hs', editable=False, max_length=200),
        ),
    ]
