# Generated by Django 3.1.5 on 2021-05-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210518_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.CharField(default='21/05/2021', editable=False, max_length=200)),
                ('pedido_cargado', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Pedido Cabecera',
                'verbose_name_plural': 'Pedido Cabeceras',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='21/05/2021 22:34:31 hs', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.pedido')),
                ('id_pedido_cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.pedidocabecera')),
            ],
            options={
                'verbose_name': 'Pedido Detalle',
                'verbose_name_plural': 'Pedido Detalle',
            },
        ),
    ]
