# Generated by Django 3.1.5 on 2021-05-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20210521_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='id_pedido_cabecera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedidocabecera'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_emision',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_vencimiento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='22/05/2021 18:01:07 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidocabecera',
            name='fecha_alta',
            field=models.CharField(default='22/05/2021', editable=False, max_length=200),
        ),
    ]
