# Generated by Django 3.1.5 on 2021-05-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_auto_20210522_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='nro_factura',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='nro_timbrado',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='22/05/2021 22:53:16 hs', editable=False, max_length=200),
        ),
    ]
