# Generated by Django 3.1.5 on 2021-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_auto_20210522_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='23/05/2021 18:46:37 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidocabecera',
            name='fecha_alta',
            field=models.CharField(default='23/05/2021', editable=False, max_length=200),
        ),
    ]
