# Generated by Django 3.1.5 on 2021-05-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_auto_20210523_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default=('PENDIENTE', 'Pendiente'), max_length=500),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_emision',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='fecha_vencimiento',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='23/05/2021 21:25:00 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='descripcion',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default='-', help_text='Ingrese email del proveedor', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(help_text='Ingrese el telefono del proveedor', max_length=500),
        ),
    ]
