# Generated by Django 3.1.5 on 2021-05-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_auto_20210523_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='factura_cargada_pedido',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_alta',
            field=models.CharField(default='29/05/2021 00:50:58 hs', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidocabecera',
            name='fecha_alta',
            field=models.CharField(default='29/05/2021', editable=False, max_length=200),
        ),
    ]
