# Generated by Django 3.1.5 on 2021-06-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='saldo_a_entregar_formateado',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_inicial_formateado',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_efectivo_formateado',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_egreso_formateado',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_ingreso_formateado',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='total_pos_formateado',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_alta',
            field=models.CharField(default='16/06/2021', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='16/06/2021 23:01:15 hs', max_length=500, null=True),
        ),
    ]
