# Generated by Django 3.1.5 on 2021-06-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='09/06/2021 22:09:08 hs', max_length=500, null=True),
        ),
    ]
