# Generated by Django 3.1.5 on 2021-06-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'default_permissions': (), 'permissions': (('add_caja', 'Agregar Caja'), ('change_caja', 'Cierre Caja'), ('delete_caja', 'Eliminar Caja'), ('view_caja', 'Listar Cajas'))},
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='09/06/2021 00:16:21 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='saldo_a_entregar',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_dia',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_egreso',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_ingreso',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
    ]
