# Generated by Django 3.1.5 on 2021-06-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_auto_20210609_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fecha_alta',
            field=models.CharField(default='09/06/2021', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='09/06/2021 00:20:46 hs', max_length=500, null=True),
        ),
    ]
