# Generated by Django 3.1.5 on 2021-06-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_auto_20210616_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='16/06/2021 23:01:57 hs', max_length=500, null=True),
        ),
    ]
