# Generated by Django 3.1.5 on 2021-07-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_auto_20210707_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='07/07/2021 22:12:14 hs', max_length=500, null=True),
        ),
    ]
