# Generated by Django 3.1.5 on 2021-02-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(help_text='Ingrese nombre del tipo de producto', max_length=200)),
                ('fecha_alta', models.CharField(default='26/02/2021 20:31:49 hs', editable=False, max_length=200)),
                ('fecha_baja', models.CharField(blank=True, default='-', max_length=200, null=True)),
            ],
        ),
    ]
