# Generated by Django 3.1.5 on 2021-02-03 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(help_text='Ingrese nombre del tipo de producto', max_length=200)),
                ('fecha_alta', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
