# Generated by Django 3.1.5 on 2021-02-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20210204_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, default='01/01/1111 00:00:00', null=True),
        ),
    ]
