# Generated by Django 3.1.5 on 2021-02-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20210204_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_baja',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
