# Generated by Django 3.1.5 on 2021-02-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20210215_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, default='00 de Enero de 0000 a las 00:00', null=True),
        ),
    ]
