# Generated by Django 3.1.5 on 2021-02-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20210215_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
