# Generated by Django 3.1.5 on 2021-02-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20210215_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, default='11/11/1111', null=True),
        ),
    ]
