# Generated by Django 3.1.5 on 2021-02-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_auto_20210215_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, default='1111-11-11 11:11:11', null=True),
        ),
    ]
