# Generated by Django 2.1 on 2021-01-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(help_text='Ingrese email del cliente', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(help_text='Ingrese ruc del cliente', max_length=200, null=True),
        ),
    ]
