# Generated by Django 2.1 on 2021-01-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20210125_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Ingrese email del cliente', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, default=models.CharField(help_text='Ingrese cedula del cliente', max_length=200), help_text='Ingrese ruc del cliente', max_length=200, null=True),
        ),
    ]
